prepare:
  settings:
    nobs: null
    split_paragraphs: true
    split_sentences: false
  star:
    usestar: 0
embed:
  settings:
    show_progress_bar: true
    batch_size: 256
    device: cpu
    num_workers: 1
  model:
    embedding_model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    use_model2vec: false
    pca_dims: 384
train:
  settings:
    top_n_words: 20
    calculate_probabilities: false
    verbose: true
  seed_topics:
    seeds:
    - - fleksibel
      - fleksibilitet
      - fleksibel arbejdstid
      - fleksibel arbejdstid
      - flekstid
      - flekstidsordning
      - flextid
      - flextidsordning
      - fixtid
      - fikstid
    - - familievenlig
      - familievenlige
      - familieliv
    - - hjemmearbejde
      - hjemmearbejdsplads
      - hjemmearbejdsdag
      - hjemmefra
    - - vagtskema
      - vagtplan
      - spidsbelastning
    - - natarbejde
      - weekend
      - weekendarbejde
      - helligdage
      - nattevagt
      - nattevagte
      - nattevagterne
      - aften
    - - ambitiøs
      - ambition
      - udvikling
      - karriere
      - udviklingsmuligheder
      - udviklingsplaner
      - udviklingsforløb
      - udviklingsprogram
    - - faglig
      - faglighed
      - sparring
    - - stillingen
      - samtaler
      - snarest muligt
      - mulig
      - ansøgning
      - ringe
      - ansøgning mail
      - ansøgning
      - sende
      - cv
      - sende ansøgning
      - ansøgning cv
      - send
      - send ansøgning
      - ansøgning sende
      - modtage ansøgning
    - - køn
      - etnisk
      - religion
      - religion etnisk
      - uanset alder
      - alder køn
      - etnisk tilhørsforhold
      - tilhørsforhold
    - - mandag
      - tirsdag
      - onsdag
      - torsdag
      - fredag
      - lørdag
      - søndag
    - - finansministeri
      - overenskomst
      - overenskomst finansministeri
      - gældende
    - - rengøringsvogn
    - - orlov
      - ferie
      - feriefridage
      - sygeorlov
      - barselsorlov
    - - bonus
      - provision
      - incitamenter
      - præstationsløn
      - salgsbonus
      - mål
      - produktivitet
    - - sundhedsforsikring
      - helbredsforsikring
      - sygeforsikring
      - sundhedsordning
      - privathospital
    - - pension
      - pensionsordning
      - arbejdsmarkedspension
      - pensionsbidrag
      - pensionsaftale
    - - kantine
      - kantineordning
      - frokostordning
      - personalekøb
    - - fitnessrum
      - kaffebar
      - ergonomisk
      - kontorfaciliteter
    - - bærbar
      - mobiltelefon
      - dataabonnement
      - værktøj
      - værnemidler
    - - sikkerhed
      - værnemidler
      - fare
      - compliance
      - sikkerhedstræning
    - - fastansættelse
      - fuldtid
      - stabilitet
      - langtidskontrakt
      - jobsikkerhed
      - anciennitet
      - tidsubegrænset
    - - tidsbegrænset
      - projektansættelse
      - midlertidig
      - midlertidigansættelse
      - prøvetidsansættelse
      - vikariat
      - kontraktansættelse
      - praktik
    - - kultur
      - værdier
      - inklusion
      - diversitet
      - bæredygtighed
      - samfundsindsats
    - - tungt
      - fysisk
      - fysiskarbejde
      - manuelt
      - anstrengende
    - - teamarbejde
      - team
      - samarbejde
      - kolleger
      - tværfaglig
      - hold
    - - uddannelse
      - læring
      - udvikling
      - karrierevækst
      - opkvalificering
      - mentoring
      - kurser
    - - sundhed
      - pleje
      - sygehus
      - klinik
    - - byggeri
      - håndværker
      - tømrer
      - murer
    - - detailhandel
      - butik
      - ekspedient
      - kasse
    - - logistik
      - lager
      - chauffør
      - truck
    - - it
      - softwareudvikler
      - programmering
      - udvikler
    - - finans
      - regnskab
      - bogholder
      - controller
    - - produktion
      - fabrik
      - montage
      - operatør
    - - uddannelse
      - lærer
      - undervisning
      - pædagog
    - - hospitality
      - restaurant
      - kok
      - tjener
    - - offentlig
      - kommune
      - rådhus
      - forvaltning
      - myndighed
      - fuldmægtig
      - ministerium
      - departement
      - styrelse
    - - kirke
      - sogn
      - menighedsråd
    - - militær
      - forsvar
      - soldat
      - officer
      - forsvarsministeri
    - - projektleder
      - projektstyring
      - planlægning
      - koordinere
    - - konsulent
      - rådgiver
      - analyse
      - implementering
    - - sosuassistent
      - social sundhedsassistent
      - pleje
      - borgerkontakt
    - - sygeplejerske
      - patient
      - klinisk
      - journal
    - - ingeniør
      - konstruktion
      - design
      - beregning
    - - elektriker
      - installation
      - fejlfinding
      - serviceopgaver
    - - kundeservicemedarbejder
      - support
      - telefon
      - kundehenvendelser
    - - maskinoperatør
      - produktion
      - vedligehold
      - skiftehold
    - - økonom
      - budget
      - controlling
      - afstemning
    - - jurist
      - kontrakt
      - lovgivning
      - compliance
    - - pædagog
      - børnehave
      - skole
      - undervisning
    name: flex1
    anchor_strength: 6
  dimensionality_reduction:
    model: UMAP
    n_neighbors: 60
    n_components: 5
    min_dist: 0.0
    metric: cosine
    random_state: 42
  clustering:
    model: HDBSCAN
    min_cluster_size: 120
    min_samples: 30
    metric: euclidean
    cluster_selection_method: eom
    prediction_data: true
evaluate:
  vectorizer:
    model: CountVectorizer
    ngram_range:
    - 1
    - 3
    min_df: 10
    max_features: 10000
  c_TF_IDF:
    model: c_TF_IDF
    bm25_weighting: true
    reduce_frequent_words: true
  representation:
    model: MMR
    diversity: 0.2
  settings:
    similarity_phrase: fleksibel
    top_n: 8
