prepare:
  settings:
    nobs: null
    split_paragraphs: true
    split_sentences: false
  star:
    usestar: 0
embed:
  settings:
    show_progress_bar: true
    batch_size: 256
    device: cpu
    num_workers: 1
  model:
    embedding_model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    use_model2vec: false
    pca_dims: 384
train:
  settings:
    top_n_words: 20
    calculate_probabilities: false
    nr_topics: null
    verbose: true
  seed_topics:
    seeds: null
  dimensionality_reduction:
    model: UMAP
    n_neighbors: 60
    n_components: 5
    min_dist: 0.0
    metric: cosine
    random_state: null
    low_memory: true
  clustering:
    model: HDBSCAN
    min_cluster_size: 1000
    min_samples: 500
    metric: euclidean
    cluster_selection_method: leaf
    prediction_data: false
evaluate:
  vectorizer:
    model: CountVectorizer
    ngram_range:
    - 1
    - 3
    min_df: 10
    max_features: 100000
  c_TF_IDF:
    model: c_TF_IDF
    bm25_weighting: false
    reduce_frequent_words: true
  representation:
    model: MMR
    diversity: 0.2
  settings:
    similarity_phrase: fleksibel
    top_n: 8
