prepare:
  settings:
    nobs: 1000
  star:
    usestar: 0
embed:
  embedding_model: intfloat/multilingual-e5-large-instruct
predict:
  top_n_words: 20
  verbose: true
  dimensionality_reduction:
    model: UMAP
  clustering:
    model: HDBSCAN
  vectorizer:
    model: CountVectorizer
  c_TF_IDF:
    model: c_TF_IDF
  representation:
    model: KeyBERTInspired
