prepare:
  settings:
    nobs: 1000
    batch_size: 50
    threads: 4
    chunk_size: 500
  preprocessing:
    model: da_core_news_lg
    pipeline:
    - tok2vec
    - lemmatizer
    keep_negations: true
  star:
    usestar: 0
predict:
  n_topics: 20
  embedding_model: all-MiniLM-L6-v2
  random_state: 42
