prepare:
  settings:
    nobs: null
    split_paragraphs: true
  star:
    usestar: 0
embed:
  settings:
    show_progress_bar: true
    batch_size: 256
    device: cpu
    num_workers: 1
  model:
    embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
    use_model2vec: false
    pca_dims: 384
train:
  settings:
    top_n_words: 20
    verbose: true
  dimensionality_reduction:
    model: UMAP
    n_neighbors: 15
    n_components: 5
    min_dist: 0.0
    metric: cosine
    random_state: 42
  clustering:
    model: HDBSCAN
    min_cluster_size: 15
    min_samples: 15
    metric: euclidean
    cluster_selection_method: eom
    prediction_data: true
  vectorizer:
    model: CountVectorizer
    ngram_range:
    - 1
    - 3
    min_df: 10
    max_features: 10000
  c_TF_IDF:
    model: c_TF_IDF
    bm25_weighting: true
    reduce_frequent_words: true
  representation:
    model: KeyBERTInspired
evaluate:
  settings:
    similarity_phrase: familievenlig
    top_n: 8
