prepare:
  settings:
    nobs: 1000
    batch_size: 50
    threads: 4
    chunk_size: 500
  preprocessing:
    model: da_core_news_lg
    pipeline:
    - tok2vec
    - lemmatizer
    keep_negations: true
  star:
    usestar: 0
