prepare:
  settings:
    nobs: 30000
    split_paragraphs: true
    split_sentences: true
  star:
    usestar: 1
embed:
  settings:
    show_progress_bar: true
    batch_size: 64
    device: null
    num_workers: 1
    shard_size: 50000
  model:
    embedding_model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    use_model2vec: false
    pca_dims: 768
train:
  settings:
    top_n_words: 20
    calculate_probabilities: false
    nr_topics: null
    verbose: true
    nobs: 1000000
  seed_topics:
    seeds: null
  dimensionality_reduction:
    model: UMAP
    n_neighbors: 60
    n_components: 5
    min_dist: 0.0
    metric: cosine
    random_state: null
    low_memory: true
    n_jobs: 16
  clustering:
    model: HDBSCAN
    min_cluster_size: 1000
    min_samples: 500
    metric: euclidean
    cluster_selection_method: leaf
    prediction_data: true
    core_dist_n_jobs: 8
predict:
  settings:
    nobs: 2000000
    clustering: false
    batch_mode: false
    full_p_dist: false
    ignore_limit: 0.5
evaluate:
  vectorizer:
    model: CountVectorizer
    ngram_range:
    - 1
    - 3
    min_df: 10
    max_features: 100000
  c_TF_IDF:
    model: c_TF_IDF
    bm25_weighting: false
    reduce_frequent_words: false
  representation:
    model: MMR
    diversity: 0.2
  label_llm:
    use_llm: true
    model: Mistral-7B-Instruct-v0.3-Q6_K.gguf
    model_folder: Mistral-7B-Instruct-v0.3-GGUF
    gpu_layers: 0
    model_type: mistral
    use_representative_docs: true
    nr_representative_docs: 5
    top_n_words: 10
    gen_kwargs:
      max_new_tokens: 16
      temperature: 0.1
      top_p: 0.95
      repetition_penalty: 1.1
  settings:
    similarity_phrase: fleksibel
    top_n: 8
    update_topics: true
    oos_prediction: false
    use_cpu: true
