defaults:
  - prepare/settings: small
  - prepare/star: local
  - embed/settings: default
  - embed/model: intfloat
  - train/settings: default
  - train/dimensionality_reduction: UMAP
  - train/clustering: HDBSCAN
  - train/vectorizer: CountVectorizer
  - train/c_TF_IDF: c_TF_IDF
  - train/representation: KeyBERTInspired
  - evaluate/settings: default
