defaults:
  - prepare/settings: small
  - prepare/star: local
  - embed: model
  - predict: settings
  - predict/dimensionality_reduction: UMAP_blank
  - predict/clustering: HDBSCAN_blank
  - predict/vectorizer: CountVectorizer_blank
  - predict/c_TF_IDF: c_TF_IDF_blank
  - predict/representation: KeyBERTInspired
